### ISSUE TITLE
 Error after activating plugin

### ISSUE THREAD

**Issue by ppierref** [Probesys/glpi-plugins-vip#1]
After activating the plugin, applicants do not appear.
![ErroPluginVIPs1 4 1](https://user-images.githubusercontent.com/35942310/105072924-1eced400-5a65-11eb-9764-ed899d1bff85.png)

**Comment by felag** [comment]
Hello @ppierref,
Thank you for your interest in this plugin.

What version of GLPi and VIP plugin are you using ?

Can you please check [latest version 1.4RC1](https://github.com/Probesys/glpi-plugins-vip/releases/tag/v1.4RC1) ?

**Comment by ppierref** [comment]
> Olá @ppierref ,
> Obrigado pelo seu interesse neste plugin.
> 
> Qual versão do GLPi e plugin VIP você está usando?
> 
> Você pode verificar a [última versão 1.4RC1](https://github.com/Probesys/glpi-plugins-vip/releases/tag/v1.4RC1) ?

I'm using a version of GLPI 9.5.3 with the VIP 1.4RC1 plugin,  PHP 7.2.0, Debian 10

**Comment by felag** [comment]
Hello,
I just installed a fresh GLPi 9.5.3 and VIP 1.4RC1 plugin from [tar.bz2 bundle](https://github.com/Probesys/glpi-plugins-vip/releases/download/v1.4RC1/glpi-plugin-vip-v1.4RC1.tar.bz2) in realese (**not** .tar.gz source code).

Problem does not show. 

Maybe problem comes from your specific installation ?
> I'm using a version of GLPI 9.5.3 with the VIP 1.4RC1 plugin, PHP 7.2.0, Debian 10

Can you please double check your php version ? ([Debian 10 ships php7.3 packages](https://packages.debian.org/search?suite=buster&keywords=php7), not php7.2.)
Do you have other plugins installed ?

Can you please try on a new installation ?

**Comment by ppierref** [comment]
I performed installation in a test environment and had an error.
Test environment similar to production:

`

Instruções de instalação e configuração
--
Verificar se uma nova versão está disponível
[code]   GLPI 9.5.3 ( => /var/www) Installation mode: TARBALL

Operating system: Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 PHP 7.3.19-1~deb10u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at 192.168.0.160 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 Server Software: Debian 10 	Server Version: 10.3.27-MariaDB-0+deb10u1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.27) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/config has been validated. Write access to /var/www/files has been validated. Write access to /var/www/files/_dumps has been validated. Write access to /var/www/files/_sessions has been validated. Write access to /var/www/files/_cron has been validated. Write access to /var/www/files/_graphs has been validated. Write access to /var/www/files/_lock has been validated. Write access to /var/www/files/_plugins has been validated. Write access to /var/www/files/_tmp has been validated. Write access to /var/www/files/_cache has been validated. Write access to /var/www/files/_rss has been validated. Write access to /var/www/files/_uploads has been validated. Write access to /var/www/files/_pictures has been validated. Write access to /var/www/marketplace has been validated. Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

GLPI_ROOT: /var/www GLPI_CONFIG_DIR: /var/www/config GLPI_VAR_DIR: /var/www/files GLPI_MARKETPLACE_DIR: /var/www/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/files GLPI_CACHE_DIR: /var/www/files/_cache GLPI_CRON_DIR: /var/www/files/_cron GLPI_DUMP_DIR: /var/www/files/_dumps GLPI_GRAPH_DIR: /var/www/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/files/_locales GLPI_LOCK_DIR: /var/www/files/_lock GLPI_LOG_DIR: /var/www/files/_log GLPI_PICTURE_DIR: /var/www/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/files/_plugins GLPI_RSS_DIR: /var/www/files/_rss GLPI_SESSION_DIR: /var/www/files/_sessions GLPI_TMP_DIR: /var/www/files/_tmp GLPI_UPLOAD_DIR: /var/www/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/locales GLPI_VERSION: 9.5.3 GLPI_SCHEMA_VERSION: 9.5.3 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/vendor/sabre/http/lib) sabre/uri in (/var/www/vendor/sabre/uri/lib) sabre/vobject in (/var/www/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/vendor/elvanto/litemoji/src) symfony/console in (/var/www/vendor/symfony/console) scssphp/scssphp in (/var/www/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/vendor/ramsey/uuid/src) psr/log in (/var/www/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/vendor/paragonie/sodium_compat/src) phpCas version 1.3.6 in (/usr/share/php/CAS/source)

Server: 'ldaps://locahost.com.br', Port: '636', BaseDN: 'OU=AADDC Users,DC=domain,DC=com,DC=br', Connection filter: 		none, RootDN: 'local@domain.com.br', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (local@domain.com.br@smtp.office365.com)

Name: 'local@domain.com.br' Active: Yes 	Server: '{outlook.office365.com:995/pop/ssl/novalidate-cert/notls}INBOX' Login: 'local@domain.com.br' Password: Yes

behaviors            Name: Comportamental                 Version: 2.2.2      State: Installed / not activated 	
formcreator          Name: Form Creator                   Version: 2.11.0-beta.1 State: Installed / not activated 	
fusioninventory      Name: FusionInventory                Version: 9.4+2.4    State: Installed / not activated 	
hidefields           Name: Hidefields                     Version: 1.0.0      State: Installed / not activated 	
manufacturersimports Name: Importação de fornecedores     Version: 2.2.1      State: Installed / not activated 	
pdf                  Name: Imprimir em PDF                Version: 1.6.0      State: Installed / not activated 	
dashboard            Name: Painel                         Version: 1.0.1      State: Installed / not activated 	
vip                  Name: VIP                            Version: 1.4RC1     State: **Enabled**
[/code]

`

**Comment by ppierref** [comment]
Version v1.4.1 of the VIP plugin is working on GLPI version 9.5.3.

^_^

**Comment by felag** [comment]
> Version v1.4.1 of the VIP plugin is working on GLPI version 9.5.3.

Hello, sorry for the delay.

How do you install plugin version v1.4RC1 ?

Regards

**Comment by Sicoval31** [comment]
Bonjour, ce probleme reste d'actualité avec une Version 9.5.7 de GLPI (PHP 8) et la dernière version du plugin (1.4RC1).
Dès l'activation du plugin, la liste des utilisateurs demandeur est vide.
Une version pour la V10 est-elle prévue ?
Application non présente dans le marketplace.
Dommage que ce plugin semble abandonné, il est utile et mérite d'être amélioré

**Comment by felag** [comment]
Hello,

a new version 1.5.0 has been released.

@ppierref Has it corrected the problem ?

**Comment by prob6** [comment]
This plugin is now co-managed with InfoTel on official GLPI plugin respository:

https://github.com/pluginsGLPI/vip

This repository is now archived (read-only).
