### ISSUE TITLE
Demandeur non selectionnable

### ISSUE THREAD

**Issue by Bapt-man** [Probesys/glpi-plugins-vip#2]
Depuis la mise en place du plugin VIP sur les profils techniques, il est impossible de sélectionner le demandeur lors de la création d'un ticket.

![image](https://user-images.githubusercontent.com/85102462/123451820-24b17e00-d5de-11eb-8f1f-db375acf9d09.png)

Je suis obligé de retirer tous les droits sur les profils sur l'onglet du plugin.
![image](https://user-images.githubusercontent.com/85102462/123452150-6cd0a080-d5de-11eb-87a6-c20e4282ec9a.png)

Sans les droits, la liste déroulante fonctionne, mais pas de colonne VIP dans les tickets.
Avec les droits, la liste déroulante ne fonctionne plus mais colonne OK.

GLPI : 9.5.5
VIP : 1.4RC1

**Comment by philg38** [comment]
Bonjour @Bapt-man ,
merci pour ce retour sur le plugin VIP.
Nous allons tâcher de répéter ce dysfonctionnement et le corriger pour pouvoir ensuite proposer une nouvelle version du plugin.
Le problème est avec des personnes ayant le profil "technicien" natif GLPI ou c'est un profil que vous avez fait vous à la main ?

**Comment by Bapt-man** [comment]
Bonjour, @philgprobesys 
Ce sont uniquement des profils créés nous même.
Mais aussi valable avec le profil super-admin.

**Comment by ghost** [comment]
Bonjour,

Je confirme que ce bug est constaté aussi bien avec les profils natifs de GLPI "technicien" ou encore "Super admin" qu'avec des profils créés manuellement.

Ce bug est toujours présent aujourd'hui en version 9.5.5 de GLPI et version 1.4RC1 du plugin VIP.

Les profils n'ayant pas les droits du plugin VIP actifs peuvent sélectionner les utilisateurs demandeurs.

Avez-vous déjà pu reproduire ce cas afin d'apporter un correctif ?

Merci d'avance pour votre retour.

**Comment by Sicoval31** [comment]
Problème similaire sur la dernière version de GLPI 9.5.6 et du plugin (désactivé pour le coup)
PHP 8.0.8

**Comment by felag** [comment]
Bonjour,

Un correctif a été apporté dans la dernière version (1.5.0).

Est-ce que cela corrige le problème chez vous ?

**Comment by Sicoval31** [comment]
1.5 ?
j'ai la 1.7.2 sur un glpi 9.5.7 où le problème n'apparait plus

**Comment by felag** [comment]
@Sicoval31 Attention, si vous êtes en version 1.7.2, il ne s'agit pas de ce plugin.

**Comment by Sicoval31** [comment]
j'ai celui-ci : 
![image](https://user-images.githubusercontent.com/42040529/188887652-48a5bba5-5110-40d5-b46f-252ac312ec0e.png)
et pas d'icone pour aller directement sur le github du plugin

**Comment by prob6** [comment]
This plugin is now co-managed with InfoTel on official GLPI plugin respository:

https://github.com/pluginsGLPI/vip

This repository is now archived (read-only).
