### ISSUE TITLE
Feature : différents types de VIP

### ISSUE THREAD

**Issue by Sicoval31** [Probesys/glpi-plugins-vip#3]
Bonjour, à ce jour, il n'existe qu'un seul type de VIP, un seul logo.
Serait-il possible de pouvoir définir différents groupes VIP et de personnaliser le logo qui apparait afind e différencier des chefs de service des directeurs, présidents, élus.
Merci

**Comment by Sicoval31** [comment]
Qui ne dit mot, consent !
Merci de prendre en compte cette proposition, j'ai hâte de pouvoir tester ça :)

**Comment by prob6** [comment]
This plugin is now co-managed with InfoTel on official GLPI plugin respository:

https://github.com/pluginsGLPI/vip

This repository is now archived (read-only).
