### ISSUE TITLE
GLPI10 version

### ISSUE THREAD

**Issue by Sicoval31** [Probesys/glpi-plugins-vip#4]
Tout est dans le titre.
Plugin non mis à jour depuis 1 an alors qu'il pose un problème de compatibilité avec la 9.5 (liste des demandeurs vides).
Une version pour glpi10 est-elle prévue ?

**Comment by philg38** [comment]
bonjour,
merci pour votre rappel, en effet il est nécessaire de mettre à jour le code de ce plugin pour le rendre fonctionnelle avec la dernière version stable de GLPI.
En ce qui concerne le fait de la porter sur GLPI 10 nous préférons pour le moment attendre que cette version soit stable et faisons par contre en sorte que nos plugins soient compatibles avec le fork GSIT de GLPI que nous préférons utiliser.

**Comment by prob6** [comment]
This plugin is now co-managed with InfoTel on official GLPI plugin respository:

https://github.com/pluginsGLPI/vip

This repository is now archived (read-only).
